services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: hospital-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/hospitaldb
    ports:
      - "5050:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: hospital-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  mongo-data: