version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/hospitaldb
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
volumes:
  mongo-data: